### ISSUE TITLE
Blocker: unable to continue with training

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/darkflow#1]
step 59 - loss 10.995342254638672 - moving ave loss 27.974873126259492 - time 22.547255516052246
Checkpoint at step 59
Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/ec2-user/tools/darkflow/darkflow/cli.py", line 29, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/home/ec2-user/tools/darkflow/darkflow/net/flow.py", line 43, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/ec2-user/tools/darkflow/darkflow/net/yolo/data.py", line 126, in shuffle
    x_batch = np.concatenate(x_batch, 0)
ValueError: need at least one array to concatenate

**Comment by nerdykamil** [comment]
Hey, any update on this?
